services:
  # May need to run:
  # sudo xhost +local:docker
  lunar-lander-actor-critic:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
    - ./src:/app
    - ./data:/data
    image: lunar-lander-actor-critic
    user: "${UID:-1000}:${UID:-1000}"

    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
